### ISSUE TITLE
Ajout Licence

### ISSUE THREAD

**Issue by jdauphant** [betagouv/django-magicauth#13]
Je recommande une MIT qui permet une large réutilisation du code.

**Comment by lazybird** [comment]
Je n'avais pas vu ce commentaire...

@jdauphant @estellecomment @Anna-Livia @raphodn : est-ce que vous avez des suggestions au sujet de la licence ?

**Comment by jdauphant** [comment]
Une license permissive, homologé par la DINUM https://www.data.gouv.fr/fr/licences
Je recommande MIT ^^

**Comment by lazybird** [comment]
Nous avons maintenant une License MIT.

PR #30
