### ISSUE TITLE
"e-contrôle notification" as title in the html email template

### ISSUE THREAD

**Issue by alemangui** [betagouv/django-magicauth#14]
The default template for the html-version of the email ([found here](https://github.com/betagouv/django-magicauth/blob/master/magicauth/templates/magicauth/email.html)) has _e-contrôle notification_ as the title.

```<title>e-contrôle notification</title>```

Note that this is a minor issue since the title is rarely seen in emails (except for when the users click on "view online" or in certain versions of Android).

An alternative would be to have a generic title, maybe something like _Accéder à {{ site.domain }}_ or use the email subject as the html title. 

Another option (perhaps overkill), would be to incorporate a setting to specify it.

Which option would you prefer? I could try to prepare a PR if needed.

**Comment by lazybird** [comment]
Thanks @alemangui for this comment and sorry for the late response.
I have opened a small PR for this. I don't think it worth having a setting, as the entire email can be overridden for customization.

PR #22

**Comment by estellecomment** [comment]
Merged.
