### ISSUE TITLE
Contact Info

### ISSUE THREAD

**Issue by codingjoe** [betagouv/django-magicauth#59]
Hi there,

Hope you're having a wonderful day. Might I suggest adding a security policy, including a contact for people wanting to submit a security issue? After all, this is an authentication related package. It would be a shame if someone couldn't properly disclose an issue.

Best
Joe

**Comment by mrjmad** [comment]
Hello and sorry for taking so long to reply.

You can write at tech@aidantsconnect.beta.gouv.fr
