### ISSUE TITLE
LOGGED_IN_REDIRECT_URL_NAME is sometimes a url, sometimes a url name

### ISSUE THREAD

**Issue by estellecomment** [betagouv/django-magicauth#6]
When we create the email link, we fill in the "next" value here :
https://github.com/betagouv/django-magicauth/blob/master/magicauth/views.py#L41-L44

By default, the "next" query_param will be `"/" + LOGGED_IN_REDIRECT_URL_NAME + "/"`. If you are actually using a url name, not a url, then that breaks the redirect.

Example using the default config : 
LOGGED_IN_REDIRECT_URL_NAME = 'control-detail'  (with associated url "/accueil")
The emailed link is : 
`https://<server>/code/<token key>/?next=/control-detail/`
So that the login process ends up redirecting on 
`https://<server>/control-detail`, which doesn't exist (the associated url which exists is `/accueil`)

Expected final redirect :`https://<server>/accueil`
(the email link itself could be `https://<server>/code/<token key>/?next=control-detail` or `https://<server>/code/<token key>/?next=/accueil`, whatever works)

Edit : second problem (I think it's separate but I could be wrong) : email.txt contains a different link from email.html.
https://github.com/betagouv/django-magicauth/blob/master/magicauth/templates/magicauth/email.html#L312 : no next_view
https://github.com/betagouv/django-magicauth/blob/master/magicauth/templates/magicauth/email.txt#L3 : has next_view

**Comment by lazybird** [comment]
This was fixe in release 0.4 in the PR : #8
