### ISSUE TITLE
Ajout d'un fichier publiccode.yml pour être promu via code.gouv.fr

### ISSUE THREAD

**Issue by bzg** [betagouv/django-magicauth#86]
Votre dépôt est référencé comme "Awesome" dans https://code.gouv.fr/fr/awesome/.

Pour ce référencement, la mission logiciels libres a créé un fichier `publiccode.yml` avec des metadonnées sur le dépôt, fichier que vous trouverez dans [ce répertoire](https://github.com/codegouvfr/awesome-codegouvfr/tree/main/dist).

D'ici octobre, nous mettrons à jour https://code.gouv.fr/sources et nous listerons les dépôt Awesome en allant chercher les métadonnées directement depuis un fichier publiccode.yml à la racine du dépôt.

Pourriez-vous rappatrier le `publiccode.yml` de [ce répertoire](https://github.com/codegouvfr/awesome-codegouvfr/tree/main/dist) et l'ajouter à votre dépôt ?

Si besoin, je peux proposer de faire la PR, vous me dites :)  Merci !

PS: https://github.com/publiccodeyml/publiccode.yml donne plus d'info sur le standard `publiccode.yml`.

**Comment by christophehenry** [comment]
Salut ! Pas de soucis, on s'en charge !

**Comment by christophehenry** [comment]
Je viens d'ouvrir un PR. Tu peux relire ?

**Comment by bzg** [comment]
Oui, ça peut être mergé, merci !

Pouvez-vous juste me dire qui finance actuellement les développements ?  C'est un prérequis pour être dans la liste Awesome.

**Comment by christophehenry** [comment]
Personne. C'est pris sur les temps de développement des projets qui l'utilisent. Principalement Aidants Connect pour le moment.

**Comment by bzg** [comment]
Mh okay. Peut-on dire que c'est "officiellement" pris sur les temps de dev de ces projets ?  Si oui, quels sont ces projets et qui les finance ?  Si non, on devra malheureusement retirer le dépôt de la liste Awesome :/

**Comment by Karel2** [comment]
Oui c'est officiellement pris sur le temps de dev du produit Aidants Connect qui est financé par les budgets de l'ANCT dans le cadre du programme société numérique.

**Comment by christophehenry** [comment]
C'est ajouté. [Tu peux valider ?](https://github.com/betagouv/django-magicauth/pull/88)
